Use ament_python to build packages rather than ament_cmake
RobotWebTools/rosbridge_suite pull request #939
Opened 2024-07-16 18:34 UTC by EricGallimore

**Public API Changes**
None

**Description**
Change the build system for these packages from `ament_cmake` to `ament_python`.  This is the suggested way to build Python packages for ROS2, and is needed for them to work under Windows.
- `rosapi`

Should resolve #914 and #921.

2024-07-16 22:23 UTC, EricGallimore commented
This PR includes the changes from #938, since they were needed to run under Windows for testing.  That PR should probably be merged first.

2024-08-14 02:01 UTC, sea-bass requested changes
Changes look good, but seems some executable files became not executable in the process. Please take a look.

2024-08-14 02:01 UTC, sea-bass commented on rosapi/rosapi/rosapi_node.py
This file seems to have some permissions changes. Can you fix this to make sure it's executable?

2024-08-14 02:01 UTC, sea-bass commented on rosbridge_server/rosbridge_server/rosbridge_websocket.py
Same here

2024-08-14 02:01 UTC, sea-bass commented on rosbridge_server/rosbridge_server/websocket_handler.py
And here

2024-08-15 17:16 UTC, EricGallimore commented
> Changes look good, but seems some executable files became not executable in the process. Please take a look.

These should be fixed, thanks.

2024-08-15 17:30 UTC, sea-bass commented
There are also some merge conflicts to address (sorry, I merged a bunch of PRs recently)

2024-08-26 19:53 UTC, EricGallimore commented
> There are also some merge conflicts to address (sorry, I merged a bunch of PRs recently)

Just rebased and merged.  Hopefully this does it.

2024-08-27 01:27 UTC, sea-bass commented
Weirdly enough, it also shows a bunch of other changes which seem to undo some of the small PRs that recently went in ... did you rebase on the latest version of the upstream `ros2` branch, or the latest that you had checked out?

2025-03-26 00:56 UTC, closed without merging