fix(params): prevent parameter retrieval crashes in ROS2
RobotWebTools/rosbridge_suite pull request #978
Opened 2024-12-05 09:00 UTC by Mehsias

**Public API Changes**
None

**Description**
- Add check for node's fully qualified name to prevent deadlocks
- Add 2.0s timeout to spin_until_future_complete
- Fix crashes when retrieving parameters via Roslibjs

Fixes #972

2025-01-04 19:08 UTC, sea-bass commented on rosapi/src/rosapi/params.py
> +        _node.executor.spin_until_future_complete(future, timeout_sec=2.0)
Changes look good, but this 2.0 may not hold in all cases. Wonder if should at least be a named constant instead of hard-coded, or even better a configurable parameter of the node?

2025-01-04 19:10 UTC, sea-bass commented on rosapi/src/rosapi/params.py
> +        _node.executor.spin_until_future_complete(future, timeout_sec=2.0)
Also, would it help to add this timeout in the `else` case right below this as well?

2025-01-10 07:40 UTC, Mehsias commented on rosapi/src/rosapi/params.py
> +        _node.executor.spin_until_future_complete(future, timeout_sec=2.0)
@sea-bass That's a good idea! I've also noticed that in params.py there is a todo saying to remove the node entirely and use rosapi instead. What do you think this would entail in terms of work?

Sorry I am fairly new to ROS and don't have much experience in its uses outside of my limited scope.

2025-01-11 17:06 UTC, sea-bass commented on rosapi/src/rosapi/params.py
> +        _node.executor.spin_until_future_complete(future, timeout_sec=2.0)
I think the comment is instead of creating a new ROS node, one could use the existing ROS node and prevent deadlocks by using a `MultiThreadedExecutor` (which many people try to avoid as it's buggy/not performant), or make better use of the async capabilities so calling a parameter retrieval service is non-blocking.

I think it would be some work, but nothing too extreme. But certainly can be done in a follow-on PR.

2025-01-13 13:56 UTC, bjsowa commented on rosapi/src/rosapi/params.py
> +        _node.executor.spin_until_future_complete(future, timeout_sec=2.0)
I made a small proof of concept [here](https://github.com/RobotWebTools/rosbridge_suite/commit/65eb74413060aa3068f132bb22d4a2e279de8644) where I removed the `rosapi_params` node and used async/await features in rclpy for listing parameter names while still using `SingleThreadedExecutor`

2025-01-13 14:34 UTC, Mehsias commented on rosapi/src/rosapi/params.py
> +        _node.executor.spin_until_future_complete(future, timeout_sec=2.0)
@bjsowa looks good! seems compatible to what I tried to do with the last push. Although I can't test it atm because my vscode always imports from /opt/.. instead of the local scripts in the workspace.

2025-01-17 06:36 UTC, Mehsias commented
@sea-bass I don't know what I did to break the whole CI. I force pushed a squashed commit because the linter check was failing, and now everything is failing.

2025-01-17 10:40 UTC, bjsowa commented
You somehow broke the `rosbridge_websocket` symlink. I can fix it if you want.

2025-01-19 16:47 UTC, bjsowa requested changes

2025-01-19 16:47 UTC, bjsowa commented on rosapi/src/rosapi/params.py
>          raise RuntimeError("Wait for list_parameters service timed out")
This function can crash if the `wait_for_service` call fails as the RuntimeError is not catched anywhere. The easiest way to make this call fail is to have a node which doesn't start it's parameter services. Here's an example:
```Python
import rclpy
rclpy.init();
node = rclpy.create_node('rosapi_test_node', start_parameter_services=False)
rclpy.spin(node)
```
As this is still related to the issue you are trying to fix (crashes during parameter retrieval), could you also fix that?

IMO we shouldn't wait 5 seconds for service to become available as this will greatly increase the response time when we are running nodes without parameter servers. If we assume the rosapi node has enough time to spin and gather information about the ROS graph, we should be good with just returning an empty list if the `list_parameters` service is not available right away:
```suggestion
    if not client.service_is_ready():
        return []
```

2025-01-25 20:55 UTC, bjsowa commented on rosapi/src/rosapi/params.py
>          raise RuntimeError("Wait for list_parameters service timed out")
Hope you don't mind me changing this myself

2025-01-25 21:21 UTC, bjsowa approved these changes

2025-01-25 21:25 UTC, merged

2025-01-27 07:28 UTC, Mehsias commented on rosapi/src/rosapi/params.py
>          raise RuntimeError("Wait for list_parameters service timed out")
hey @bjsowa! Thanks so much for finishing this up. I've had the flu and wasn't able to get anything done.